# .gitlab-ci.yml
variables:
  DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
  DOCKER_IMAGE: "$DOCKERHUB_USERNAME/${CI_PROJECT_NAME}"
  KUBE_NAMESPACE: "default"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - apt-get update
    - apt-get install -y curl gettext-base
    # Install kubectl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    # Setup kubeconfig
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - chmod 400 ~/.kube/config
  script:
    - kubectl version --client
    # Menggunakan envsubst untuk mengganti variabel
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl get pods -n $KUBE_NAMESPACE
  only:
    - main