# .gitlab-ci.yml
variables:
  DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
  DOCKER_IMAGE: "$DOCKERHUB_USERNAME/${CI_PROJECT_NAME}"
  KUBE_NAMESPACE: "default"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - chmod 400 ~/.kube/config
  script:
    - kubectl version
    - kubectl create namespace $KUBE_NAMESPACE || true
    - |
      kubectl apply -f - <<EOF
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${CI_PROJECT_NAME}
        namespace: ${KUBE_NAMESPACE}
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: ${CI_PROJECT_NAME}
        template:
          metadata:
            labels:
              app: ${CI_PROJECT_NAME}
          spec:
            containers:
            - name: ${CI_PROJECT_NAME}
              image: ${DOCKER_IMAGE}:${CI_COMMIT_SHA}
              ports:
              - containerPort: 8080
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: ${CI_PROJECT_NAME}
        namespace: ${KUBE_NAMESPACE}
      spec:
        selector:
          app: ${CI_PROJECT_NAME}
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
        type: ClusterIP
      EOF
  only:
    - main