apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl
  labels:
    name: nginx-curl
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-curl
  template:
    metadata:
      name: nginx-curl
      labels:
        name: nginx-curl
    spec:
      containers:
        - name: nginx-curl
          image: ${DOCKER_IMAGE}:${CI_COMMIT_SHA}
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-curl-web-service
spec:
  type: NodePort
  selector:
    name: nginx-curl
  ports:
    - port: 3000
      targetPort: 8000
      nodePort: 8001
