apiVersion: batch/v1
kind: Job
metadata:
  name: python-job
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: python-job
          image: p4ck/python-job
